### ISSUE TITLE
オドメトリ情報の取得方法について

### ISSUE THREAD

**Issue by TomoyaKishimoto** [Field-Robotics-Japan/vtc_unity#1]
芝浦工業大学　機械制御工学研究室の岸本と申します。

現在、VTC on Unity環境の地図生成のためにROSメッセージとしてオドメトリ情報の取得を試みているのですが、オドメトリ情報は3DLiDARやIMUなどと同様に取得できるパッケージはあるのでしょうか？

**Comment by RyodoTanaka** [comment]
@TomoyaKishimoto 
Issue ありがとうございます．
オドメトリ取得に関するパッケージはまだ提供しておりません．
今月（8月）末までに実装し，ご案内したいと思います．
よろしくお願いします．

**Comment by TomoyaKishimoto** [comment]
分かりました、お忙しい中早急に対応していただきありがとうございます。

**Comment by RyodoTanaka** [comment]
すみません...！
本件まだ対応できていないのでRe-Openさせていただきます...！
要望が多いがまだ実装できていないものは以下のとおりです．

- [ ] Wheel Odometry の観測
- [ ] 2D LiDARの実装
