### ISSUE TITLE
地面のデータに付きまして

### ISSUE THREAD

**Issue by OITYukiInoue** [Field-Robotics-Japan/vtc_unity#2]
大阪工大　井上雄紀と申します。READMEにある手順でcloneしましたが、地面のデータが点群としてはあるのですが、/vtc_unity/Assets/vtc_world_unity/Scenes/vtc_world.unityを用いてシーンを開いた場合にモデルに含まれません。現在３Dオブジェクトとして高さ0mのところにPlaneを１つ加えることでテストを始めております。どのようにして路面データを組み込むか手順を教えていただけませんでしょうか。

**Comment by RyodoTanaka** [comment]
@OITYukiInoue 
ご迷惑をおかけしており，申し訳ありません．
実は同様のIssueが world データのみのリポジトリhttps://github.com/Field-Robotics-Japan/vtc_world_unity/issues/8 でも起こっておりました．
原因は， `git lfs`の利用と `blender` のバージョン，プラグインのインストールが必要であるためでした．
現在，Blenderとの依存をなくすために，すべてPrefab展開したものをリリース予定です（https://github.com/Field-Robotics-Japan/vtc_world_unity/issues/9）．
ご迷惑をおかけし申し訳ありませんが，そちらをお待ちいただくか，https://github.com/Field-Robotics-Japan/vtc_world_unity より，最新のWorldデータをダウンロードし，ご利用いただけると幸いです．
よろしくお願いします．

**Comment by RyodoTanaka** [comment]
@OITYukiInoue 
井上 先生
こちらで地面ファイルのPrefab展開などを試しましたが，Blenderファイルを直接importしており，環境データの編集の都合上，直接importの形式を変更することは難しいです．
そこで，お手数をおかけしますが，Unityを起動するPC環境に
- Blender 2.8 以上をダウンロードする
- ダウンロードしたBlenderに Poiut Cloud Viewer をダウンロードする
- `vtc_unity`を再ロードする

という手順をお願いしたく思います．
詳しい説明は下記のREADMEをご覧ください．
https://github.com/Field-Robotics-Japan/vtc_world_unity#installation

以上，何卒よろしくお願いします．

**Comment by OITYukiInoue** [comment]
ご案内頂いた方法に付きまして vtc_world_unityについては、ファイルを一度削除して後で指示の方法でデータができることを確認いたしました。 当初うまく行かなかった理由についてはBlender のバージョンがxenial (Ubuntu 1604)ではリボジトリのppt追加を行っても2.7版しか導入されないことでした。
http://ubuntuhandbook.org/index.php/2019/07/blender-2-80-released-how-to-install-in-ubuntu-16-04-18-04/

にあるように、snapを用いてBlender >=2.8を満たすものを導入することでこの問題は解決しました。

**Comment by RyodoTanaka** [comment]
@OITYukiInoue 
うまく動作し，良かったです！
本リポジトリのREADMEにInstallationを追加しておきます．
環境データなど現在もアップデートをしております．
今後もどうぞよろしくお願いします．

READMEに追加次第，本PRを閉じたいと思います．
よろしくお願いします．

**Comment by RyodoTanaka** [comment]
README を追加しましたので閉じます．
https://github.com/Field-Robotics-Japan/vtc_unity#installation

@OITYukiInoue 
井上先生，ありがとうございました．
